name: 'Publish artifacts'
description: 'Sample deployment'
inputs:
  username:
    description: 'Login username'
    required: true
  password:
    description: 'Login password'
    required: true
outputs:
  hostname:
    description: 'url to the deployed app'
runs:
  using: 'node12'
  main: 'index.js'
